name: SDSkyblockCore
version: '1.0.1-SNAPSHOT'
main: org.sumit282698.sDSkyblockCore.SDSkyblockCore
api-version: '1.21'

commands:
  sbget:
    description: Get a custom Skyblock item
    usage: /<command> <id>